blank_issues_enabled: false
contact_links:
  - name: 質問は Discord でお願いします
    url: https://healthy-person-emulator.org/readme
    about: 判断に迷う場合はこのリンクよりDiscord招待が掲載されているサイトへアクセスし、Discord招待を探し、招待を受け、Discordで質問してください
